// Movies
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH';
export const RECEIVE_FAVMOVIES = 'RECEIVE_FAVMOVIES';
export const SET_USER = 'SET_USER';


